# Generated by Django 5.0.6 on 2024-05-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
    ]
