# Generated by Django 5.0.6 on 2024-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_remove_user_age_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='daily_rental_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
